import Birches from "../media/booksMedia/birches.jpeg";
import firrNice from "../media/booksMedia/firrNice.jpeg";
import harryPotter from "../media/booksMedia/harryPotter.jpeg";
import HarryPotter2 from "../media/booksMedia/HarryPotter2.jpeg";
import homeBurial from "../media/booksMedia/homeBurial.jpeg";
import Relativity from "../media/booksMedia/Relativity.jpeg";
export const BookData = [
  {
    id: "1",
    name: "Great Truths That Set Us Free",
    authorName: "Dr. Joseph Murphy",
    publishedDate: "2 Aug, 2000",
    price: "500",
    rating: "4.5",
    img: Birches,
    // authorImg:
  },
  {
    id: "2",
    name: "HArry potter",
    authorName: "JK Rowling",
    publishedDate: "2 March, 2001",
    price: "700",
    rating: "3.5",
    img: firrNice,
  },

  {
    id: "3",
    name: "ONE PEICE",
    authorName: "ODA",
    publishedDate: "3 Sep, 1999",
    price: "1500",
    rating: "4.2",
    img: harryPotter,
  },

  {
    id: "4",
    name: "MOB PYSCHO",
    authorName: "ONE",
    publishedDate: "3 Sep, 1999",
    price: "1500",
    rating: "4.2",
    img: Birches,
  },
  {
    id: "5",
    name: "ONE PUNCH MAN",
    authorName: "ONE",
    publishedDate: "3 Sep, 1999",
    price: "1500",
    rating: "4.2",
    img: HarryPotter2,
  },
  {
    id: "6",
    name: "BERSERK",
    authorName: "Kentaro Miura",
    publishedDate: "3 Sep, 1999",
    price: "1500",
    rating: "4.2",
    img: firrNice,
  },

  {
    id: "7",
    name: "Harry Potter and the Half-Blood Prince",
    authorName: "JK Rowling",
    publishedDate: "2 Aug, 2000",
    price: "500",
    rating: "4.5",
    img: homeBurial,
  },
  {
    id: "8",
    name: "Calculus -3",
    authorName: "Dave gray",
    publishedDate: "2 March, 2001",
    price: "700",
    rating: "3.5",
    img: Relativity,
  },

  {
    id: "9",
    name: "Calculus -2",
    authorName: "Dave Gray",
    publishedDate: "3 Sep, 1999",
    price: "1500",
    rating: "4.2",
    img: homeBurial,
  },

  {
    id: "10",
    name: "Calculus -1",
    authorName: "Dave Gray",
    publishedDate: "3 Sep, 1999",
    price: "1500",
    rating: "4.2",
    img: Birches,
  },
  {
    id: "11",
    name: "ART OF WAR",
    authorName: "SANSU",
    publishedDate: "3 Sep, 1999",
    price: "1500",
    rating: "4.2",
    img: firrNice,
  },
  {
    id: "12",
    name: "Naruto",
    authorName: "Masashi Kishimoto",
    publishedDate: "3 Sep, 1999",
    price: "1500",
    rating: "4.2",
    img: Relativity,
  },

  {
    id: "13",
    name: "666 Satan",
    authorName: "Seishi Kishimoto",
    publishedDate: "2 Aug, 2000",
    price: "500",
    rating: "4.5",
    img: firrNice,
  },
  {
    id: "14",
    name: "Boruto",
    authorName: "Mikio Ikemoto",
    publishedDate: "2 March, 2001",
    price: "700",
    rating: "3.5",
    img: homeBurial,
  },
  {
    id: "15",
    name: "Relativity : the special and the general theory",
    authorName: "Albert Einstein",
    publishedDate: "2 March, 2001",
    price: "700",
    rating: "3.5",
    img: HarryPotter2,
  },

  {
    id: "16",
    name: "Cosmos",
    authorName: "Carl Sagan",
    publishedDate: "3 May, 1995",
    price: "700",
    rating: "3.5",
    img: harryPotter,
  },
  {
    id: "17",
    name: "Home Burial",
    authorName: "Robrt Frost",
    publishedDate: "12 March, 1914",
    price: "700",
    rating: "3.5",
    img: HarryPotter2,
  },
  {
    id: "18",
    name: "Birches",
    authorName: "Robert Frost",
    publishedDate: "21 July, 1915",
    price: "700",
    rating: "3.5",
    img: homeBurial,
  },
  {
    id: "19",
    name: "fire - ice",
    authorName: "Robert Frost",
    publishedDate: "2 March, 1920",
    price: "700",
    rating: "3.5",
    img: firrNice,
  },
  {
    id: "20",
    name: "Bleach",
    authorName: "Tite Kuba",
    publishedDate: "2 Aug, 1999",
    price: "700",
    rating: "3.5",
    img: homeBurial,
  },
];
